# -*- coding: utf-8 -*-
"""
Created on Sun Jan  2 06:46:34 2022
TEST CASE 001
@author: bhanu
"""
from selenium import webdriver
import time
import requests
with open("test_case_001"+".txt","w+") as f:
    f.write("\ninitiating test case 001........")
    f.write("\nordering a product using valid credentials , first login then order the product from necklace and pendants")
    driver = webdriver.Chrome(executable_path="C:\chromedriver.exe")
    driver.maximize_window()
    f.write("\ndriver has been opended in maximized window...")
    f.write("\nchrome driver opens...")
    url = "https://meraldajewels.com/"
    driver.get(url)
    time.sleep(3)
    
    f.write("\nwebsite meraldajewels.com is open.....")
    url = ("current url is : ",driver.current_url)
    url = str(url)
    f.write("\n"+url)
    title = ("current title is : ",driver.title)
    title = str(title)
    f.write("\n"+title)
    usr_logo = driver.find_element_by_xpath("//*[@id='homeMainnavBar']/div[1]/div[2]/div/div/ul/li[2]/a")
    usr_logo.click()
    f.write("\nredirected to the login page.... ")
    url = ("current url is : ",driver.current_url)
    url = str(url)
    f.write("\n"+url)
    title = ("current title is : ",driver.title)
    title = str(title)
    f.write("\n"+title)
    time.sleep(3)
    usr_email = "springr.test@gmail.com"
    pass_wrd = "qwer1234"
    
    username = driver.find_element_by_xpath("//*[@id='shippingForm']/div[1]/div/div[1]/input")
    username.send_keys(usr_email)
    password = driver.find_element_by_xpath("//*[@id='shippingForm']/div[1]/div/div[2]/input")
    password.send_keys(pass_wrd)
    submit = driver.find_element_by_xpath("//*[@id='shippingForm']/div[3]/button")
    submit.click()
    f.write("\nvalid credentials has been entered and clicked on 'Login'...")
    time.sleep(3)
    f.write("\nredirected to the homepage after login")
    url = ("current url is : ",driver.current_url)
    url = str(url)
    f.write("\n"+url)
    title = ("current title is : ",driver.title)
    title = str(title)
    f.write("\n"+title)
    
    jewellery = driver.find_element_by_xpath("//*[@id='homeMainnavBarDrop']/div/ul/li[2]/a")
    jewellery.click()
    necklace_pendant = driver.find_element_by_xpath("//*[@id='homeMainnavBarDrop']/div/ul/li[2]/div/div/div/ul[1]/li[2]/a")
    necklace_pendant.click()
    time.sleep(3)
    f.write("\nclicked on jewellery then on necklace and pendants..")
    f.write("\nthis has been redirected to necklace and pendant page...")
    url = ("current url is : ",driver.current_url)
    url = str(url)
    f.write("\n"+url)
    title = ("current title is : ",driver.title)
    title = str(title)
    f.write("\n"+title)
    
    driver.execute_script("window.scrollTo(0,800)")
    time.sleep(3)
    f.write("\nscroll to the first product..")
    pend_1 = driver.find_element_by_xpath("//*[@id='homeMainContent']/section[2]/div/div[2]/div/div/div[1]/a[2]")
    pend_1.click()
    time.sleep(3)
    f.write("\nclick on the first product and it redirects to product page...")
    url = ("\ncurrent url is : ",driver.current_url)
    url = str(title)
    f.write("\n"+url)
    title = ("current title is : ",driver.title)
    title = str(title)
    f.write("\n"+title)
    driver.execute_script("window.scrollTo(0,300)")
    time.sleep(1)
    f.write("\nscroll to make add to cart visible...")
    add_to_cart = driver.find_element_by_xpath("//*[@id='homeMainContent']/section[1]/div/div/div[2]/div/form/div[3]/button")
    add_to_cart.click()
    time.sleep(3)
    f.write("\nclick on add to cart .....")
    
    cart = driver.find_element_by_xpath("//*[@id='scrollNavbr']/div[3]/div/div/div/ul/li[4]/a")
    cart.click()
    time.sleep(3)
    f.write("\nclicked on cart, and it redirects to cart page...")
    url = ("current url is : ",driver.current_url)
    url = str(title)
    f.write("\n"+url)
    title = ("current title is : ",driver.title)
    title = str(title)
    f.write("\n"+title)
    driver.execute_script("window.scrollTo(0,200)")
    time.sleep(1)
    #product = driver.find_element_by_xpath("//*[@id='homeMainContent']/section[1]/div/div[2]/div[1]/div/form/div[1]/div[2]/h4/a")
    element = driver.find_element_by_xpath("//*[@id='homeMainContent']/section[1]/div/div[2]/div[1]/div/form/div[1]/div[2]/h4/a").text
    #f.write(element)
    assert element == 'Estelle Oval Pendant with Chain'
    f.write("\nchecked that product is present in cart...")
    driver.execute_script("window.scrollTo(0,350)")
    f.write("\nscroll to checkout...")
    checkout = driver.find_element_by_xpath("//*[@id='homeMainContent']/section[1]/div/div[2]/div[2]/div/ul/li[5]/a")
    checkout.click()
    f.write("\nclicked on checkout and redirects to the checkout...")
    url = ("current url is : ",driver.current_url)
    url = str(url)
    f.write("\n"+url)
    title = ("current title is : ",driver.title)
    title = str(title)
    f.write("\n"+title)
    time.sleep(3)
    # scroll to continue button then click on continue button
    driver.execute_script("window.scrollTo(0,300)")
    time.sleep(1)
    cont = driver.find_element_by_xpath("//*[@id='shippingForm']/div/button")
    cont.click()
    time.sleep(3)
    f.write("\nclicked on continue button, should redirect to payment gateway page...")
    url = ("current url is : ",driver.current_url)
    url = str(url)
    f.write("\n"+url)
    title = ("current title is : ",driver.title)
    title = str(title)
    f.write("\n"+title)
    
    driver.quit()


